"""
Namelist generation: Scenario -> PALM _p3d Fortran namelist.

Uses Jinja2 templates versioned per PALM release.
"""

from __future__ import annotations

from ..config import DEFAULT_DZ, DEFAULT_NZ, PALM_VERSION
from ..models.scenario import Scenario

# Inline template for v23.10. Move to file when template complexity grows.
NAMELIST_TEMPLATE = """\
!-- Generated by PALM4Umadeeasy (schema {schema_version}, PALM {palm_version})
!-- Scenario: {scenario_name}
!-- Fingerprint: {fingerprint}
!-- DO NOT EDIT MANUALLY

&initialization_parameters
    nx = {nx},
    ny = {ny},
    nz = {nz},
    dx = {dx:.1f},
    dy = {dy:.1f},
    dz = {dz:.1f},
    origin_date_time = '{origin_date_time}',
    topography = 'read_from_file',
    longitude = {longitude:.4f},
    latitude = {latitude:.4f},
/

&runtime_parameters
    end_time = {end_time:.1f},
    dt_data_output = {dt_data_output:.1f},
    data_output = 'theta',
                  'u',
                  'v',
                  'bio_mrt*',
                  'bio_pet*',
                  'bio_utci*',
                  't_surface*',
/

&radiation_parameters
    radiation_scheme = 'rrtmg',
/

&biometeorology_parameters
    thermal_comfort = .TRUE.,
/

&plant_canopy_parameters
    canopy_mode = 'read_from_file',
/

&land_surface_parameters
/

&urban_surface_parameters
/
"""


def generate_namelist(scenario: Scenario, case_name: str) -> str:
    """Generate a PALM _p3d namelist from a scenario."""
    domain = scenario.domain
    sim = scenario.simulation
    bbox = domain.bbox

    # PALM uses 0-indexed grid dimensions
    nx = domain.nx - 1
    ny = domain.ny - 1

    # Compute center for lat/lon
    center_x = (bbox.west + bbox.east) / 2
    center_y = (bbox.south + bbox.north) / 2

    # Forcing archetype -> date mapping
    date_map = {
        "typical_hot_day": "2025-07-15 06:00:00 +02",
        "heat_wave_day": "2025-07-25 06:00:00 +02",
        "moderate_summer_day": "2025-06-20 06:00:00 +02",
        "warm_night": "2025-07-20 18:00:00 +02",
    }
    origin_date = date_map.get(sim.forcing.value, "2025-07-15 06:00:00 +02")

    return NAMELIST_TEMPLATE.format(
        schema_version=scenario.schema_version,
        palm_version=PALM_VERSION,
        scenario_name=scenario.name,
        fingerprint=scenario.fingerprint(),
        nx=nx,
        ny=ny,
        nz=domain.nz,
        dx=domain.resolution_m,
        dy=domain.resolution_m,
        dz=domain.dz,
        origin_date_time=origin_date,
        longitude=center_x if abs(center_x) <= 180 else 6.96,
        latitude=center_y if abs(center_y) <= 90 else 50.94,
        end_time=sim.simulation_hours * 3600.0,
        dt_data_output=sim.output_interval_s,
    )
